engines:
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
exclude_paths:
- tests/
- matl_online/static/vendor/
